allowBuilds:
  msgpackr-extract: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vite-plus: 0.2.1
minimumReleaseAgeExclude:
  - "@effect/tsgo-darwin-arm64@0.14.2"
  - "@effect/tsgo-darwin-x64@0.14.2"
  - "@effect/tsgo-linux-arm64@0.14.2"
  - "@effect/tsgo-linux-arm@0.14.2"
  - "@effect/tsgo-linux-x64@0.14.2"
  - "@effect/tsgo-win32-arm64@0.14.2"
  - "@effect/tsgo-win32-x64@0.14.2"
  - "@effect/tsgo@0.14.2"
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
