import { expect, test } from "vite-plus/test";
import {
  LineAccountManagement,
  LineRepository,
  LineClientRegistry,
  LineMessages,
  LineTextMessage,
  makeLineApiClient,
  verifyLineSignature,
  verifyLineSignatureString,
  makeLineLoginClient,
  makeLineLiffClient,
  LineApiAuthenticationError,
  LineApiRateLimitError,
  LineApiResponseError,
  LineApiTimeoutError,
  LineSignatureError,
  LineLoginApiAuthenticationError,
  LineLoginApiRateLimitError,
  LineLoginApiResponseError,
  LineLoginApiTimeoutError,
  ProviderView,
  ChannelView,
  LiffAppView,
} from "../src/index.ts";

test("exports the stable LINE manager API", () => {
  expect([
    LineAccountManagement,
    LineRepository,
    LineClientRegistry,
    LineMessages,
    LineTextMessage,
    makeLineApiClient,
    verifyLineSignature,
    verifyLineSignatureString,
    makeLineLoginClient,
    makeLineLiffClient,
    LineApiAuthenticationError,
    LineApiRateLimitError,
    LineApiResponseError,
    LineApiTimeoutError,
    LineSignatureError,
    LineLoginApiAuthenticationError,
    LineLoginApiRateLimitError,
    LineLoginApiResponseError,
    LineLoginApiTimeoutError,
    ProviderView,
    ChannelView,
    LiffAppView,
  ]).not.toContain(undefined);
});
