import { expect, test } from "vite-plus/test";
import {
  LiffAppView,
  LineApiAuthenticationError,
  LineApiRateLimitError,
  LineApiResponseError,
  LineApiTimeoutError,
  LineClientRegistry,
  LineLiffApps,
  LineLoginApiAuthenticationError,
  LineLoginApiRateLimitError,
  LineLoginApiResponseError,
  LineLoginApiTimeoutError,
  LineLoginChannels,
  LineMessages,
  LineMessagingChannels,
  LineProviders,
  LineSignatureError,
  LineTextMessage,
  ProviderView,
  makeLineApiClient,
  makeLineLiffClient,
  makeLineLoginClient,
  verifyLineSignature,
  verifyLineSignatureString,
} from "../src/index.ts";

test("exports the stable LINE manager API", () => {
  expect([
    LineProviders,
    LineMessagingChannels,
    LineLoginChannels,
    LineLiffApps,
    LineClientRegistry,
    LineMessages,
    LineTextMessage,
    makeLineApiClient,
    verifyLineSignature,
    verifyLineSignatureString,
    makeLineLoginClient,
    makeLineLiffClient,
    LineApiAuthenticationError,
    LineApiRateLimitError,
    LineApiResponseError,
    LineApiTimeoutError,
    LineSignatureError,
    LineLoginApiAuthenticationError,
    LineLoginApiRateLimitError,
    LineLoginApiResponseError,
    LineLoginApiTimeoutError,
    ProviderView,
    LiffAppView,
  ]).not.toContain(undefined);
});
