import { expect, test } from "vite-plus/test";
import {
  CreateLineAccountInput,
  LineAccount,
  LineChannelRecordId,
  LineChannelId,
  LineLoginChannelId,
  LineLiffId,
  LineRepository,
  LineClientRegistry,
  LineMessages,
  LineTextMessage,
  makeLineApiClient,
  verifyLineSignature,
  verifyLineSignatureString,
  makeLineLoginClient,
  makeLineLiffClient,
  LineApiAuthenticationError,
  LineApiRateLimitError,
  LineApiResponseError,
  LineApiTimeoutError,
  LineSignatureError,
  LineLoginApiAuthenticationError,
  LineLoginApiRateLimitError,
  LineLoginApiResponseError,
  LineLoginApiTimeoutError,
} from "../src/index.ts";

test("exports the stable LINE manager API", () => {
  expect([
    CreateLineAccountInput,
    LineAccount,
    LineChannelRecordId,
    LineChannelId,
    LineLoginChannelId,
    LineLiffId,
    LineRepository,
    LineClientRegistry,
    LineMessages,
    LineTextMessage,
    makeLineApiClient,
    verifyLineSignature,
    verifyLineSignatureString,
    makeLineLoginClient,
    makeLineLiffClient,
    LineApiAuthenticationError,
    LineApiRateLimitError,
    LineApiResponseError,
    LineApiTimeoutError,
    LineSignatureError,
    LineLoginApiAuthenticationError,
    LineLoginApiRateLimitError,
    LineLoginApiResponseError,
    LineLoginApiTimeoutError,
  ]).not.toContain(undefined);
});
